import type { I2pdPinnedRelease } from './i2pd-release-policy.js'

export const I2PD_LOG_FILE_SIZE = 10 * 1024 * 1024
export const I2PD_LOG_FILE_COUNT = 5

/** Generates the complete private runtime config for one trusted release. */
export function renderManagedI2pdConfig(
  release: Pick<I2pdPinnedRelease, 'logPolicy'>,
  input: Readonly<{ bandwidthClass: string; samHost: string; samPort: number }>,
) {
  const logging = release.logPolicy === 'bounded-v1'
    ? [
        'loglevel = warn',
        'logclftime = true',
        `logfilesize = ${I2PD_LOG_FILE_SIZE}`,
        `logfilecount = ${I2PD_LOG_FILE_COUNT}`,
      ]
    : []

  return [
    '# Generated by Qortium Home; regenerated on each managed start.',
    `bandwidth = ${input.bandwidthClass}`,
    'pidfile = i2pd.pid',
    'log = file',
    'logfile = i2pd.log',
    ...logging,
    '',
    '[sam]',
    'enabled = true',
    `address = ${input.samHost}`,
    `port = ${input.samPort}`,
    '',
    '[httpproxy]',
    'enabled = false',
    '',
    '[socksproxy]',
    'enabled = false',
    '',
    '[http]',
    'enabled = false',
    '',
  ].join('\n')
}
