import assert from 'node:assert/strict'
import {
  I2PD_LOG_FILE_COUNT,
  I2PD_LOG_FILE_SIZE,
  renderManagedI2pdConfig,
} from './i2pd-config.js'

const input = { bandwidthClass: 'X', samHost: '127.0.0.1', samPort: 7656 } as const
const legacy = renderManagedI2pdConfig({ logPolicy: 'legacy-unbounded' }, input)
const bounded = renderManagedI2pdConfig({ logPolicy: 'bounded-v1' }, input)

for (const config of [legacy, bounded]) {
  assert.match(config, /^# Generated by Qortium Home/m)
  assert.match(config, /^pidfile = i2pd\.pid$/m)
  assert.match(config, /^log = file$/m)
  assert.match(config, /^logfile = i2pd\.log$/m)
  assert.match(config, /^address = 127\.0\.0\.1$/m)
  assert.match(config, /^port = 7656$/m)
}

assert.doesNotMatch(legacy, /^loglevel\s*=/m)
assert.doesNotMatch(legacy, /^logclftime\s*=/m)
assert.doesNotMatch(legacy, /^logfilesize\s*=/m)
assert.doesNotMatch(legacy, /^logfilecount\s*=/m)

assert.match(bounded, /^loglevel = warn$/m)
assert.match(bounded, /^logclftime = true$/m)
assert.match(bounded, new RegExp(`^logfilesize = ${I2PD_LOG_FILE_SIZE}$`, 'm'))
assert.match(bounded, new RegExp(`^logfilecount = ${I2PD_LOG_FILE_COUNT}$`, 'm'))
assert.equal(I2PD_LOG_FILE_SIZE, 10_485_760)
assert.equal(I2PD_LOG_FILE_COUNT, 5)

console.log('Version-aware managed i2pd configuration tests passed.')
