// Pure, platform-agnostic QDN app-bridge action-name lists — the single source of
// truth for the `qdnRequest` action surface. Imported by BOTH the Electron
// main-process bridge (electron/qdn.ts) and the renderer/Android fallback bridge
// (src/platform.ts) so the action names are defined in exactly one place.
//
// This file MUST stay pure string-literal data: no Electron, Node, DOM, or
// Capacitor imports, no runtime logic. That is what lets the renderer import it
// (via Vite/Bundler) and the Electron main process import it (via NodeNext)
// without dragging platform-specific code into the wrong build graph. The
// platform-specific request/sign/approval handlers stay separate by design.

export const QDN_WRITE_ACTIONS = ['PUBLISH_MULTIPLE_QDN_RESOURCES', 'PUBLISH_QDN_RESOURCE', 'DELETE_QDN_RESOURCE'] as const;
export const QDN_ACCOUNT_AVATAR_ACTIONS = ['SET_ACCOUNT_AVATAR'] as const;
export const QDN_GROUP_ACTIONS = [
  'ADD_GROUP_ADMIN',
  'APPROVE_GROUP_JOIN_REQUEST',
  'CANCEL_GROUP_BAN',
  'CANCEL_GROUP_INVITE',
  'CREATE_GROUP',
  'GROUP_APPROVAL',
  'GROUP_BAN',
  'GROUP_KICK',
  'INVITE_TO_GROUP',
  'JOIN_GROUP',
  'LEAVE_GROUP',
  'REMOVE_GROUP_ADMIN',
  'SET_GROUP',
  'SET_GROUP_AVATAR',
  'UPDATE_GROUP',
] as const;
export const QDN_NAME_ACTIONS = [
  'BUY_NAME',
  'CANCEL_SELL_NAME',
  'REGISTER_NAME',
  'SELL_NAME',
  'UPDATE_NAME',
] as const;
// PAYMENT and SEND_COIN are aliases for the same coin-transfer transaction.
export const QDN_PAYMENT_ACTIONS = ['PAYMENT', 'SEND_COIN', 'TRANSFER_ASSET'] as const;
export const QDN_FOREIGN_WALLET_READ_ACTIONS = [
  'GET_USER_WALLET',
  'GET_WALLET_BALANCE',
  'GET_USER_WALLET_INFO',
  'GET_USER_WALLET_TRANSACTIONS',
] as const;
export const QDN_FOREIGN_CHAIN_READ_ACTIONS = [
  'GET_CROSSCHAIN_BLOCKCHAINS',
  'GET_CROSSCHAIN_SERVER_INFO',
  'GET_FOREIGN_FEE',
  'GET_SERVER_CONNECTION_HISTORY',
] as const;
export const QDN_FOREIGN_SERVER_ACTIONS = ['SET_CURRENT_FOREIGN_SERVER'] as const;
export const QDN_MARKET_PRICE_ACTIONS = ['GET_MARKET_PRICES'] as const;
export const QDN_POLL_ACTIONS = ['CREATE_POLL', 'UPDATE_POLL', 'VOTE_ON_POLL'] as const;
export const QDN_TRUST_ACTIONS = ['RATE_ACCOUNT', 'RATE_RESOURCE'] as const;
export const QDN_RATING_READ_ACTIONS = ['GET_RESOURCE_RATING', 'GET_ACCOUNT_RATING'] as const;
export const QDN_LIST_WRITE_ACTIONS = ['ADD_TO_LIST', 'REMOVE_FROM_LIST'] as const;
export const QDN_LIST_ACTIONS = ['GET_ALL_LISTS', 'GET_LIST', ...QDN_LIST_WRITE_ACTIONS] as const;
export const QDN_CHAT_ACTIONS = ['SEND_CHAT_MESSAGE'] as const;
// A deliberately narrow MESSAGE path for contracts. It is kept apart from
// chat: only AT recipients, plaintext text, no payment, and fee=0 are allowed.
export const QDN_AT_MESSAGE_ACTIONS = ['SEND_MESSAGE'] as const;
export const QDN_PRIVATE_GROUP_CHAT_READ_ACTIONS = [
  'GET_PRIVATE_GROUP_ACTIVE_CHATS',
  'SEARCH_PRIVATE_GROUP_CHAT_MESSAGES',
] as const;
export const QDN_PRIVATE_GROUP_CHAT_WRITE_ACTIONS = [
  'REQUEST_PRIVATE_GROUP_CHAT_KEY',
  'RESOLVE_PRIVATE_GROUP_CHAT_KEY_REQUESTS',
] as const;
export const QDN_PRIVATE_DIRECT_CHAT_READ_ACTIONS = [
  'GET_PRIVATE_DIRECT_ACTIVE_CHATS',
  'SEARCH_PRIVATE_DIRECT_CHAT_MESSAGES',
] as const;
export const QDN_NODE_SETTINGS_WRITE_ACTIONS = ['RESTART_NODE', 'UPDATE_NODE_SETTINGS'] as const;
export const QDN_NODE_SETTINGS_ACTIONS = ['GET_NODE_SETTINGS_METADATA', ...QDN_NODE_SETTINGS_WRITE_ACTIONS] as const;
export const QDN_HOME_SETTINGS_ACTIONS = ['GET_HOME_SETTINGS_METADATA', 'GET_HOME_SETTINGS', 'UPDATE_HOME_SETTINGS'] as const;
export const QDN_BOOKMARK_MANAGER_ACTIONS = ['BOOKMARKS_HAS_PERMISSION', 'BOOKMARKS_GET', 'BOOKMARKS_APPLY', 'BOOKMARKS_OPEN'] as const;
export const QDN_NOTIFICATION_MANAGER_ACTIONS = [
  'NOTIFICATION_MANAGER_HAS_PERMISSION',
  'NOTIFICATION_MANAGER_GET',
  'NOTIFICATION_MANAGER_SET_MUTED',
  'NOTIFICATION_MANAGER_REMOVE_RULES',
  'NOTIFICATION_MANAGER_REVOKE',
] as const;
export const QDN_ACCOUNT_FREE_WRITE_ACTIONS = [
  ...QDN_NODE_SETTINGS_WRITE_ACTIONS,
  ...QDN_LIST_WRITE_ACTIONS,
] as const;
export const QDN_APP_BRIDGE_ACTIONS = [
  'FETCH_NODE_API',
  'FETCH_ACCOUNT_AVATAR',
  'FETCH_GROUP_AVATAR',
  'FETCH_QDN_RESOURCE',
  'FETCH_QORTAL_NODE_API',
  'FETCH_QORTAL_RESOURCE',
  'GET_ACCOUNT_DATA',
  'GET_ACCOUNT_GROUPS',
  'GET_ACCOUNT_GROUP_JOIN_REQUESTS',
  'GET_ACCOUNT_NAMES',
  'GET_ACTIVE_CHATS',
  'GET_ADMIN_GROUP_JOIN_REQUESTS',
  'GET_BALANCE',
  'GET_QORT_BALANCE',
  ...QDN_FOREIGN_CHAIN_READ_ACTIONS,
  ...QDN_MARKET_PRICE_ACTIONS,
  'GET_GROUP',
  'GET_GROUP_BANS',
  'GET_GROUP_JOIN_REQUESTS',
  'GET_GROUP_KICKS',
  'GET_GROUP_MEMBERS',
  'GET_HOST_INFO',
  'GET_MEMBER_BANS',
  'GET_MEMBER_KICKS',
  'GET_MINTING_STATUS',
  'GET_NAME_DATA',
  'GET_NODE_INFO',
  ...QDN_NODE_SETTINGS_ACTIONS,
  ...QDN_HOME_SETTINGS_ACTIONS,
  ...QDN_BOOKMARK_MANAGER_ACTIONS,
  ...QDN_NOTIFICATION_MANAGER_ACTIONS,
  'GET_NODE_STATUS',
  'GET_SELECTED_ACCOUNT',
  'GET_QDN_RESOURCE_METADATA',
  'GET_QDN_RESOURCE_PROPERTIES',
  'GET_QDN_RESOURCE_STATUS',
  'GET_QDN_RESOURCE_URL',
  'GET_QORTAL_ACCOUNT_GROUPS',
  'GET_QORTAL_ACCOUNT_NAMES',
  'GET_QORTAL_ACTIVE_CHATS',
  'GET_QORTAL_CHAT_MESSAGE',
  'GET_QORTAL_CHAT_MESSAGES',
  'GET_QORTAL_NAME_DATA',
  'GET_QORTAL_NODE_STATUS',
  'GET_QORTAL_PRIMARY_NAME',
  'GET_QORTAL_TRANSACTION',
  'GET_QORTAL_RESOURCE_METADATA',
  'GET_QORTAL_RESOURCE_STATUS',
  'GET_QORTAL_RESOURCE_URL',
  'IS_USING_PUBLIC_NODE',
  'LIST_GROUPS',
  'LIST_QDN_RESOURCES',
  'OPEN_NEW_TAB',
  'OPEN_CURRENT_TAB',
  'OPEN_QDN_DOCUMENT_VIEWER',
  'OPEN_QDN_MEDIA_PLAYER',
  'RESOLVE_IDENTITIES',
  'SAVE_QDN_RESOURCE',
  'SELECT_QDN_PUBLISH_SOURCE',
  'SEND_QORT',
  'SEND_QORTAL_GROUP_CHAT',
  ...QDN_AT_MESSAGE_ACTIONS,
  ...QDN_WRITE_ACTIONS,
  ...QDN_ACCOUNT_AVATAR_ACTIONS,
  ...QDN_GROUP_ACTIONS,
  ...QDN_NAME_ACTIONS,
  ...QDN_PAYMENT_ACTIONS,
  ...QDN_FOREIGN_WALLET_READ_ACTIONS,
  ...QDN_FOREIGN_SERVER_ACTIONS,
  ...QDN_POLL_ACTIONS,
  ...QDN_TRUST_ACTIONS,
  ...QDN_RATING_READ_ACTIONS,
  ...QDN_LIST_ACTIONS,
  ...QDN_CHAT_ACTIONS,
  ...QDN_PRIVATE_DIRECT_CHAT_READ_ACTIONS,
  ...QDN_PRIVATE_GROUP_CHAT_READ_ACTIONS,
  ...QDN_PRIVATE_GROUP_CHAT_WRITE_ACTIONS,
  'REMOVE_MINTING_ACCOUNT',
  'SEARCH_CHAT_MESSAGES',
  'SEARCH_GROUPS',
  'SEARCH_QDN_RESOURCES',
  'SEARCH_QORTAL_RESOURCES',
  'SEARCH_QORTAL_TRANSACTIONS',
  'START_MINTING',
  'UNLOCK_SELECTED_ACCOUNT',
  'WHICH_UI',
  'SHOW_ACTIONS',
  'SHOW_NOTIFICATION',
  'NOTIFICATION_HAS_PERMISSION',
  'NOTIFICATION_ADD',
  'NOTIFICATION_GET',
  'NOTIFICATION_REMOVE',
] as const;

export const QDN_MINTING_ACTIONS = ['START_MINTING', 'REMOVE_MINTING_ACCOUNT'] as const;

// Actions that require a local/trusted node or protected local context, so they
// cannot succeed on a public/network node and are filtered out of
// SHOW_ACTIONS there — apps that gate UI off SHOW_ACTIONS then hide controls that
// would otherwise throw. SEND_CHAT_MESSAGE, SEND_MESSAGE, and QDN write actions
// are intentionally NOT here: their keyless paths sign locally and work against
// public nodes without handing a private key to the node.
const QDN_LOCAL_WRITE_ONLY_ACTIONS = new Set<string>([
  ...QDN_NODE_SETTINGS_ACTIONS,
  ...QDN_ACCOUNT_AVATAR_ACTIONS,
  ...QDN_GROUP_ACTIONS,
  ...QDN_NAME_ACTIONS,
  ...QDN_PAYMENT_ACTIONS,
  ...QDN_FOREIGN_WALLET_READ_ACTIONS,
  ...QDN_FOREIGN_SERVER_ACTIONS,
  // Poll actions are appended dynamically after a compatible public capability probe.
  ...QDN_POLL_ACTIONS,
  ...QDN_TRUST_ACTIONS,
  ...QDN_LIST_ACTIONS,
  ...QDN_MINTING_ACTIONS,
]);

// The actions SHOW_ACTIONS reports on a public/network node (everything that can
// actually succeed there).
export const QDN_PUBLIC_NODE_BRIDGE_ACTIONS: readonly string[] = QDN_APP_BRIDGE_ACTIONS.filter(
  (action) => !QDN_LOCAL_WRITE_ONLY_ACTIONS.has(action),
);
