export const SETTINGS_TEXT = {
  actions: {
    checkForUpdates: 'Check for updates',
    checking: 'Checking',
    downloadUpdate: 'Download update',
    downloading: 'Downloading',
    installApprovedUpdate: 'Install approved update',
    installCore: 'Install Core',
    installJava: 'Install Java',
    installUpdate: 'Install update',
    installing: 'Installing',
    openFile: 'Open file',
    save: 'Save',
    saving: 'Saving',
    startCore: 'Start Core',
    starting: 'Starting',
    stopCore: 'Stop Core',
    stopping: 'Stopping',
    test: 'Test',
    testing: 'Testing',
  },
  channels: {
    prerelease: 'Prerelease',
    stable: 'Stable',
  },
  labels: {
    channel: 'Channel',
    approvedUpdate: 'Approved update',
    coreLog: 'Core log',
    currentNode: 'Current node',
    digest: 'Digest',
    endpoint: 'Endpoint',
    errorLog: 'Error log',
    java: 'Java',
    latest: 'Latest',
    language: 'Language',
    localApi: 'Local API',
    mode: 'Mode',
    node: 'Node',
    platform: 'Platform',
    runLog: 'Run log',
    runtime: 'Runtime',
    runtimeDirectory: 'Runtime directory',
    runtimeIssue: 'Runtime issue',
    size: 'Size',
    status: 'Status',
    textSize: 'Text size',
    theme: 'Theme',
    version: 'Version',
    releaseChannel: 'Release channel',
  },
  sections: {
    displaySettings: 'Display Settings',
    nodeSettings: 'Node Settings',
    qortiumCore: 'Qortium Core',
    qortiumHome: 'Qortium Home',
  },
  status: {
    checking: 'Checking',
    current: 'Current',
    detected: 'Detected',
    downloaded: 'Downloaded',
    downloading: 'Downloading',
    javaRequired: 'Java required',
    localCoreDetected: 'Local Core detected',
    noCompatibleInstaller: 'No compatible installer',
    notInstalled: 'Not installed',
    ready: 'Ready',
    runtimeBlocked: 'Runtime needs reset',
    stopped: 'Stopped',
    unavailable: 'Unavailable',
    unsupported: 'Unsupported',
    upToDate: 'Up to date',
    updateAvailable: 'Update available',
  },
};
